service: miranda-backend
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
provider:
  name: aws
  region: eu-west-3
  environment:
    TOKEN_SECRET: ${env:TOKEN_SECRET}
    MONGO_STRING: ${env:MONGO_STRING}
  runtime: nodejs20.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true 